#!/usr/bin/python3
import sys


def factorize(num):
    """ Generate 2 factors for a given number"""
    factor1 = 2
    while num % factor1:
        if factor1 * factor1 > num:
            return (num, 1)
        factor1 += 1

    factor2 = num // factor1
    return (factor1, factor2)


if len(sys.argv) != 2:
    sys.exit(f"Wrong usage: {sys.argv[0]} <file_path>")

filename = sys.argv[1]

try:
    with open(filename, 'r') as file:
        for line in file:
            num = int(line.rstrip())
            factor1, factor2 = factorize(num)
            print(f"{num}={factor1}*{factor2}")
except FileNotFoundError:
    sys.exit("Error: File not found.")
except ValueError:
    sys.exit("Error: Invalid input. Please make sure the file contains valid integers.")
except Exception as e:
    sys.exit(f"An unexpected error occurred: {e}")
