#!/usr/bin/python3
"""Factorize given set of positive numbers in a file into the product of two small numbers."""
from sys import argv


def factorize(number_to_check):
    """Find two small numbers that multiply to give a given number."""
    i = 2

    if number_to_check < 2:
        print("Cannot factorize numbers less than 2.")
        return

    while i * i <= number_to_check:
        if number_to_check % i == 0:
            print(
                "{:.0f} = {:.0f} * {:.0f}".format(
                    number_to_check, i, number_to_check // i
                )
            )
            return
        i += 1

    print("{:.0f} is a prime number.".format(number_to_check))


if len(argv) != 2:
    print("Usage: {} <filename>".format(argv[0]))
    exit(1)

try:
    with open(argv[1], "r") as file:
        for line in file:
            try:
                number_to_check = int(line.strip())
                factorize(number_to_check)
            except ValueError:
                print(
                    "Error: Invalid input - '{}' is not a valid integer.".format(
                        line.strip()
                    )
                )
except FileNotFoundError:
    print("Error: File not found.")
except Exception as e:
    print("An unexpected error occurred:", e)
