#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys


def is_prime(n):
    """Check if a number is prime"""
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


def factorize():
    """
    A function to search file and factorize the given set of numbers into two prime numbers (format n = p*q)
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                num = int(line_number.strip())
                if num % 2 == 0:
                    print("{}={}*{}".format(num, 2, num // 2))
                    continue
                for i in range(3, num // 2 + 1, 2):
                    if num % i == 0 and is_prime(i) and is_prime(num // i):
                        print("{}={}*{}".format(num, i, num // i))
                        break
                else:
                    print("{}={}*{}".format(num, num, 1))
    except (IndexError, FileNotFoundError):
        pass


if __name__ == "__main__":
    factorize()
